### ISSUE TITLE
请教，下载完成后自动设置的问题！

### ISSUE THREAD

**Issue by leonyff** [Suwmlee/ikaros#11]
### 自动化问题
我有两个目录存放不同的视频，想要设置下载之后自动刮削链接，刮削目录哪里我看说明，能配置多目录，用 `;` 号隔开，我配置了多个不起作用，是不是是在刮削配置下只能配置一个刮削目录的原因?
![image](https://user-images.githubusercontent.com/38803732/162612546-99b54181-153a-4dae-a668-0763717d2b1e.png)

现在只能，配一个刮削目录，此目录下载完自动刮削链接。
另一个目录只能配置下载完成转移，然后再在刮削配置中手动修改刮削！
能不能刮削目录也可以设置多对？

### 文件过滤
就是能刮削是能否对这些不需要的文件进行过滤，只刮削转移需要的文件？
![image](https://user-images.githubusercontent.com/38803732/162612758-98d53cf4-223c-4071-9529-5a3b8e635278.png)
刮削后文件路径显示问题

### 转移文件权限
转移后的文件权限是 root ，用户没办法操作
![image](https://user-images.githubusercontent.com/38803732/162614983-085d9a79-ba4d-4aee-b176-13706ae82262.png)
能否在 docker 中加入环境变量: `PUID`、`PGID`

**Comment by Suwmlee** [comment]
1. 多个刮削目录没测试，我稍后看看
2. 转移没做过多限制，因为各种命名非常复杂，也可以手动选择屏蔽某个文件，之后不会再次转移。或者考虑加一个文件大小过滤
3. 路径显示是之前在avdc里修复路径的bug，这里就没做修改
4. 我是直接转移/刮削后放到emby库的，emby有管理权限可以正常读取，你这里修改是需要什么操作吗？

**Comment by Suwmlee** [comment]
- [ ] 配置多个输出目录？
- [x] 增加最小文件大小限制
- [x] 优化显示
- [x] 增加 PUID,GUID

**Comment by leonyff** [comment]
> * [ ]  配置多个输出目录？
> * [x]  增加最小文件大小限制
> * [x]  优化显示
> * [x]  增加 PUID,GUID

### 1. 多个目录刮削
默认是所有的文件放在同一个目录下，例如：`av/.....`，所以多个源目录，目的地只有一个。
而，我这边是按照，有码 或者 无码  分类来放置的，所以就需要配置多组刮削
| 源目录           | 动作        | 目的地              |
| ----------------- | ----------- | ------------------- |
| `/downloads/有码` | 刮削+硬链接 | `/media/adult/有码` |
| `/downloads/无码` | 刮削+硬链接 | `/media/adult/无码` |
**或者说可以配置有码和无码输出路径，在刮削的时候，判断影片是否有码，放置到对应配置的目的地目录也可以**
> 这个属于分类，我觉的可以参考这个项目的分类方法，可以自定义分类，自动分类影片到不同目的文件夹：
> [https://github.com/jxxghp/nas-tools](https://github.com/jxxghp/nas-tools)
> 它的分类配置文件：[https://github.com/jxxghp/nas-tools/blob/master/config/default-category.yaml](https://github.com/jxxghp/nas-tools/blob/master/config/default-category.yaml)

### 2. 刮削过滤
过滤可以后缀名，文件大小，文件名过滤把，一般下载的里面的垃圾文件名都是固定的
### 权限问题
程序处理后，root权限，如果需要手动修改的化，要到控制台命令修改比较麻烦

### 自动化脚本
刚才测试了，qb 的自动化脚本，我手动运行了下，报错了，我不太懂哪里的问题
![image](https://user-images.githubusercontent.com/38803732/162675706-65b1be4d-965b-41a7-9869-216aaf96a328.png)

**Comment by Suwmlee** [comment]
多目录的再考虑下怎么处理。一般都会有无码，有码tag。封面就会有相应的标记，而且可以自定义tag，所以直接根据tag输出不同文件夹，并不一定合理。emby可以直接根据tag过滤，不太需要去干预

因为都是pt下载，很少遇到垃圾文件，目前根据文件大小过滤，或者手动忽略。后续问题多的话，再修改

docker增加了GUID了

你用了tr的脚本。qb是用 qbcomplete.sh

**Comment by leonyff** [comment]
> 
感谢，我马上更新看看

那就是，web 界面 qb 显示的脚本有问题！
![image](https://user-images.githubusercontent.com/38803732/162682781-c3517cda-40b9-4c4b-b4f6-a666c0130fce.png)

我脚本改成了，qb的，手动测试还是不行 怎么？
![image](https://user-images.githubusercontent.com/38803732/162682988-ffe816a1-556d-4012-a0db-310d47292915.png)

**Comment by Suwmlee** [comment]
把这个脚本路径放到qbit的下载完成配置里
qbit下载完种子后，会带参数传进去

**Comment by Suwmlee** [comment]
查看下日志

**Comment by leonyff** [comment]
> 查看下日志, 在 选择 tab里或者查看database目录下web.log文件

找到问题原因了，shell 问题，应该用 bash 而不是 sh 。
使用bash 执行 成功了
![image](https://user-images.githubusercontent.com/38803732/162686506-0bb02703-ce6b-443d-b6b4-af20163c2272.png)

**Comment by Suwmlee** [comment]
多目录问题，建议新开一个issue，考虑下怎么解决

其他没问题的话，把这个关闭了

**Comment by leonyff** [comment]
> 多目录问题，建议新开一个issue，考虑下怎么解决
> 
> 其他没问题的话，把这个关闭了

好的，我单独开一个 issue
有没有考虑添加消息推送，企业微信消，pushdeer,什么的？

**Comment by leonyff** [comment]
@Suwmlee 
看你更新了，我更新了 docker容器，下载 完成执行自动任务有这个报错！最后成功是手动执行的！
**ikaros日志：**
![image](https://user-images.githubusercontent.com/38803732/163326279-1585a0e7-9116-426b-94c8-a0b86a03a394.png)

**Comment by Suwmlee** [comment]
嗯，感谢告知。这个修复还没更新到GitHub上

#13  计划和tg的通知一起提交，稍等

**Comment by leonyff** [comment]
> 嗯，感谢告知。这个修复还没更新到GitHub上
> 
> #13 计划和tg的通知一起提交，稍等
> 
> 临时解决方案：更新下自动界面的刮削、转移配置。现在不需要手动输入路径了

还有一个，qb脚本，自动执行，你配置里参数 是 %D %N，有问题。
%N 种子名称，并不是实际存储的目录名称
![image](https://user-images.githubusercontent.com/38803732/163341582-690d9bf3-fc05-4195-bbdb-8caeb2e20bde.png)
实际存储目录：**SDJS-141**
![image](https://user-images.githubusercontent.com/38803732/163341920-f1b1478b-dd76-4b1f-b155-04f7bdda70a6.png)

-----
经过我测试，可以只用一个参数：`%F` 就可以

![image](https://user-images.githubusercontent.com/38803732/163342298-f361cf1f-0976-4523-8b55-5d6fdc96bf84.png)

```shell
#!/bin/bash

QB_DOWNLOADS="${1}"
curl -XPOST http://127.0.0.1:12345/api/client -H 'Content-Type: application/json' \
--data @<(cat <<EOF
{"path":"$QB_DOWNLOADS"}
EOF
)

```
