### ISSUE TITLE
[Feature Request] support multi scraping config

### ISSUE THREAD

**Issue by Suwmlee** [Suwmlee/ikaros#12]
#11

**Comment by leonyff** [comment]
> 🎉 This issue has been resolved in version 1.23.0 🎉
> 
> The release is available on:
> 
> * `v1.23.0`
> * [GitHub release](https://github.com/Suwmlee/ikaros/releases/tag/v1.23.0)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

看你更新了，我更新了 docker容器，下载 完成执行自动任务有这个报错！
**ikaros日志：**
![image](https://user-images.githubusercontent.com/38803732/163326279-1585a0e7-9116-426b-94c8-a0b86a03a394.png)
