### ISSUE TITLE
只想要一个批量命名功能.哈哈

### ISSUE THREAD

**Issue by 277383761** [Suwmlee/ikaros#23]
因为jav有jav的emby插件可以刮削了.现在只想要一键批量命名的功能.最好是检测到S1或S01文件夹的情况下,子目录里的智能预设批量命名成S1E1 S1E2之类的.同理检测到S2或S02的子目录就全部命名成S2E1 S2E2

**Comment by Suwmlee** [comment]
在重命名tab里有
