### ISSUE TITLE
用npm反代https，没办法打开web端。。

### ISSUE THREAD

**Issue by leo8912** [Suwmlee/ikaros#24]
如题，直接端口转发可以打开web，但是反代了就无法打开。。。有办法吗？

**Comment by leo8912** [comment]
用穿透，无端口的反代就可以打开。。

**Comment by Suwmlee** [comment]
👍 

不清楚你怎么配置的，web源码 https://github.com/Suwmlee/ikaros-web

PS: 此项目没做权限管理，暴露到公网环境，有一定风险
