### ISSUE TITLE
【功能请求】刮削输出模式，添加 复制文件 选项

### ISSUE THREAD

**Issue by leonyff** [Suwmlee/ikaros#28]
由于我的，下载目录和存储目录不在同一个，存储空间 没法使用硬链接，现使用 ikaros 中配置输出模式为：移动文件，会导致 qbittorrent 显示丢失文件，没办法做完上传，自动删除任务
![image](https://user-images.githubusercontent.com/38803732/227973219-0eb5ba5a-f914-4d73-b6cd-46c28d6296aa.png)
![image](https://user-images.githubusercontent.com/38803732/227973526-ec231f72-de95-4f5c-bfa1-7877191fbb7c.png)

能否，在刮削选项中，加一个输出模式为  "**复制文件**"

**Comment by Suwmlee** [comment]
如果时因为无法上传，可以设置qbit，复制下载完成的文件到xxxx，ikaros对xxxx目录进行刮削
