### ISSUE TITLE
群晖docker下的重命名是没法显示预览吗

### ISSUE THREAD

**Issue by sfsama** [Suwmlee/ikaros#30]

**Comment by sfsama** [comment]
[https://s1.ax1x.com/2023/05/06/p9akFjH.jpg](url)

**Comment by sfsama** [comment]
https://s1.ax1x.com/2023/05/06/p9akFjH.jpg

**Comment by Suwmlee** [comment]
可以
选择目录后，点击预览按钮

如果看不到，确认下映射路径和文件访问权限

**Comment by sfsama** [comment]
> 可以 选择目录后，点击预览按钮
> 
> 如果看不到，确认下映射路径和文件访问权限

开始是可以正常显示，更改多次以后就没法正常显示了，看日志还在正常工作

**Comment by sfsama** [comment]
原来是只能英文标题呀

**Comment by Suwmlee** [comment]
应该没有中英区分

麻烦给下具体的文件名，我复现下

**Comment by sfsama** [comment]
> 应该没有中英区分
> 
> 麻烦给下具体的文件名，我复现下

现在发现，应该是手动命名过集数，导致不能识别

**Comment by Suwmlee** [comment]
哦，如果集数命名正确，不需要修改，是不会显示的。页面缺少提示，之后增加一下
