### ISSUE TITLE
大小限制

### ISSUE THREAD

**Issue by bestruirui** [Suwmlee/ikaros#31]
这个大小限制是大于设置的大小的文件吗
是这样设置的吗
![image](https://github.com/Suwmlee/ikaros/assets/89796393/5adf5793-4a84-4845-a56f-282bbed35ac2)

**Comment by Suwmlee** [comment]
只需要输入数字就好

忽略大小低于这个值的文件

**Comment by bestruirui** [comment]
好的，谢谢
还有就是单位是什么，kb，mb？

**Comment by Suwmlee** [comment]
MB

忽略小于此值的文件,单位:MB。设置为0则不限制

~~奇怪，之前有提示的，可能哪次修改清除了~~

**Comment by bestruirui** [comment]
好的好的，谢谢
