### ISSUE TITLE
/init: 37: exec: s6-overlay-suexec: Exec format error

### ISSUE THREAD

**Issue by sunnyadams** [Suwmlee/ikaros#40]
/init: 37: exec: s6-overlay-suexec: Exec format error

**Comment by Suwmlee** [comment]
需要更多描述

**Comment by nuannuandexiyang** [comment]
https://blog.csdn.net/weixin_47028810/article/details/131745812

**Comment by Suwmlee** [comment]
suwmlee/ikaros:latest

docker版本未复现
