### ISSUE TITLE
刮削failed文件夹清空了

### ISSUE THREAD

**Issue by ender049** [Suwmlee/ikaros#49]
docker，挂载media
media下有待刮削影片和trim，failed两个以前mdc刮削后的文件夹，里面都是影片
刮削启动后，failed文件夹清空了……
5个多T没有了，嗯，佛系了
![image](https://github.com/Suwmlee/ikaros/assets/12645631/376f570c-d6fe-4c5b-a896-ed9fcad8bb9c)

**Comment by Suwmlee** [comment]
😢 不要忧桑，会有更好的影片
