### ISSUE TITLE
刮削识别id异常

### ISSUE THREAD

**Issue by Suwmlee** [Suwmlee/ikaros#52]
LUXU-1xxx SIRO-xxxx nhdtb-xxxxx MXGS-xxxx HODV-xxxxx MDSR-xxxx heyzo-xxxx

#51

**Comment by zz99906** [comment]
我还反映了一下别的问题，有时间你可以看看，

**Comment by zz99906** [comment]
dsvr-xxxx   GANA-xxxx我又发现了2个，可以一起

**Comment by zz99906** [comment]
SKY-xxx-1.
