### ISSUE TITLE
aria2配置自动脚本后，TG无法通知

### ISSUE THREAD

**Issue by 13465256354** [Suwmlee/ikaros#55]
使用aria2下载器配置自动脚本后，刮削正常，TG的token和chatid经测试也正常，但是自动刮削完成TG不会通知

**Comment by 13465256354** [comment]
![1](https://github.com/Suwmlee/ikaros/assets/113293304/2f528906-e547-481a-ac75-88b159b4f27e)
![2](https://github.com/Suwmlee/ikaros/assets/113293304/dd9e291f-17a4-4108-83ef-051916f3c770)

**Comment by Suwmlee** [comment]
未复现，会多增加一些调试日志信息

**Comment by Suwmlee** [comment]
请使用最新版，查看debug日志
