### ISSUE TITLE
能否强制重新刮削

### ISSUE THREAD

**Issue by Hxalan** [Suwmlee/ikaros#59]
第一次刮削的时候不知道为啥只下载了封面，没有下载nfo文件，现在点击开始都跳过了

**Comment by Suwmlee** [comment]
数量不多的话，可以手动点击右侧刮削。多的话，如果使用的是链接方式，批量删除记录

**Comment by zz99906** [comment]
> 数量不多的话，可以手动点击右侧刮削。多的话，如果使用的是链接方式，批量删除记录

parathd-xxxx  这个也显示后面没有p
