### ISSUE TITLE
不清楚是BUG还是别的问题，作者进来看

### ISSUE THREAD

**Issue by zz99906** [Suwmlee/ikaros#61]
自动刮削时候，代理网络不通连接失败，就会造成刮削界面显示进行中，即使重新代理连接通了，这个进行中还是无法消除，过不去了，

**Comment by Suwmlee** [comment]
可以手动修改状态

**Comment by zz99906** [comment]
> 可以手动修改状态

我就是手动的，自动不行

**Comment by FeverKing** [comment]
> > 可以手动修改状态
> 
> 我就是手动的，自动不行

fixed: [dc16](https://github.com/Suwmlee/ikaros/commit/dc16881f55b4c7023531222bc0222cd3d23a2d1d)
