### ISSUE TITLE
国产 AV 

### ISSUE THREAD

**Issue by qiniuweihe** [Suwmlee/ikaros#69]
国产AV 有支持的数据源吗？

**Comment by Suwmlee** [comment]
目前使用的 [刮削库](https://github.com/Suwmlee/scrapinglib )

**Comment by qiniuweihe** [comment]
麻豆用的啥啊，madouqu 的网站上有这个番号 MDHT-0018 但是没识别

**Comment by qiniuweihe** [comment]
<img width="1861" alt="image" src="https://github.com/user-attachments/assets/0e1d5452-d698-40f5-8cb8-54e43f474ce0">

**Comment by Suwmlee** [comment]
使用 MDHT0018

或者在详情里指定库和地址
