### ISSUE TITLE
希望能在刮削时重命名，而不是直接修改源文件

### ISSUE THREAD

**Issue by hbzjwyz** [Suwmlee/ikaros#72]
例如：源文件名为【hhd800.com@ipx-123.mp4】
当前重命名：通过【hhd800.com@】替换为【】,重命名后源文件名为【ipx-123.mp4】
这种情况会影响源文件做种
如果不替换则会以hhd800作为番号
希望更新后：通过设置规则，可以在刮削的时候将【hhd800.com@ipx-123.mp4】替换未【ipx-123.mp4】去刮削

**Comment by Suwmlee** [comment]
使用硬链接。下载目录可以继续做种

**Comment by hbzjwyz** [comment]
还有一个，修改功能只能单个修改，不能批量修改，且只能单个重试，不能批量重试。
例如：我有四个文件 ipx-123-A.mp4，ipx-456-A.mp4，ipx-123-B.mp4，ipx-456-B.mp4。我现在要分别点开4个文件，把A的分片为1，B的分片为2。再分别单独重试4次，切不能同时重试，这个能否实现多选后，批量操作

**Comment by Suwmlee** [comment]
在重构新的项目，会保存刮削的元数据，不需要多次刮削
